# Generated by Django 5.1.3 on 2025-01-18 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hotel', '0002_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='hotel',
            name='image',
            field=models.ImageField(default='default_image.jpg', upload_to='hotels'),
        ),
    ]
